@startuml
hide empty description

state FR1 {
  ' This only works for 1 FR, then it breaks because this is globally unique
  FlowPersistence : RemovedAfterProceeding
  PresentationType : NavigationStack
}

FR2 : FlowPersistence : RemovedAfterProceeding
FR2 : PresentationType : NavigationStack

' This is what an empty example looks like with "hide empty description" on.
state FR3

state FR4 {
  note bottom of FR4
    FlowPersistence : RemovedAfterProceeding
  end note
  note bottom of FR4
    PresentationType : NavigationStack
  end note
}

state FR5 {
  ' Notes still have to be unique in the file
  note "FlowPersistence : RemovedAfterProceeding" as FR5.FlowPersistence
  note "PresentationType : NavigationStack" as FR5.PresentationType
}

state FR6 {
  [*] --> FR6.FlowPersistence : RemovedAfterProceeding
  [*] --> FR6.PresentationType : NavigationStack
}

state FR7 {
  FR7.FlowPersistence : RemovedAfterProceeding
  FR7.PresentationType : NavigationStack
}

state FlowPersistenceSelection {
  state RemovedAfterProceeding
  state PersistWhenSkipped
}

state FR8 {
  [*] -up-> RemovedAfterProceeding
}

state FR9 {
  state FR9.Configuration
  note bottom of FR9.Configuration
    test
  end note
}

state FR10 {
  state "FR10\nFlowPersistence" : RemovedAfterProceeding
  state "FR10\nPresentationType" : NavigationStack
}

FR1 -> FR2
FR2 -> FR3
FR3 --> FR8
FR8 --> FR4
FR4 --> FR5
FR5 --> FR6
FR6 -left-> FR7
FR7 --> FR9
FR9 -left-> FR10


state SelectOnlineOptionScreen
state SelectPhysicalLocationView
state SelectEventType
state SelectDateAndTime
state LoginOrSignup
state GatherBasicUserInfo
state ConfirmEvent
state LongLoadingScreen {
  note "FlowPersistence : RemovedAfterProceeding" as LongLoadingScreen.FlowPersistence
  note "PresentationType : NavigationStack" as LongLoadingScreen.PresentationType
}
state IrreversableCompletionScreen
IrreversableCompletionScreen  : FlowPersistence : RemovedAfterProceeding
IrreversableCompletionScreen  : PresentationType : NavigationStack



[*] --> SelectOnlineOptionScreen
SelectOnlineOptionScreen --> SelectPhysicalLocationView
SelectPhysicalLocationView --> SelectEventType
SelectEventType --> SelectDateAndTime
SelectDateAndTime -> LoginOrSignup
LoginOrSignup -> GatherBasicUserInfo
GatherBasicUserInfo -> ConfirmEvent
ConfirmEvent --> LongLoadingScreen
LongLoadingScreen --> IrreversableCompletionScreen
IrreversableCompletionScreen --> [*]
@enduml